/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'afahsl' at '6/8/15 9:53 AM' with Gradle 2.4
 *
 * @author afahsl, @date 6/8/15 9:53 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
